enable_project_categories: true # enables categorization of projects into multiple categories

display_categories: [Active, Inactive, Unmaintained, Abandoned]
collections:
  plugins:
    output: true
    permalink: /:collection/:title/