enable_project_categories: true # enables categorization of projects into multiple categories

remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - label: Fancy
    children:
      - AutoSuspend

collections:
  plugins:
    output: true
    permalink: /:collection/:title/