url: https://jurassicplayer.github.io/decky-plugins-unofficial-compendium
project_url: https://github.com/jurassicplayer/decky-plugins-unofficial-compendium
maintainer: jurassicplayer

enable_project_categories: true # enables categorization of projects into multiple categories

display_categories: [Active, Inactive, Unmaintained, Abandoned]
collections:
  plugins:
    output: true
    permalink: /:collection/:title/
  api:
    output: true
    permalink: /:collection/:title/