name: Update Store Data
on:
  schedule:
  - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  query_store:
    runs-on: ubuntu-latest
    outputs:
      isNew: ${{ steps.compare.outputs.isNew }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Hash local store data
        run: echo "STORE_SHA=$(sha256sum ./docs/_data/store.json)" >> $GITHUB_ENV
      - run: ls ./
      - name: Poll and hash fresh store data
        run: |
          curl https://plugins.deckbrew.xyz/plugins > ./docs/_data/store.json
          echo "NEW_STORE_SHA=$(sha256sum ./docs/_data/store.json)" >> $GITHUB_ENV
      - name: Compare hashes
        id: compare
        run: |
          if [[ "$STORE_SHA" != "$NEW_STORE_SHA" ]]; then
            echo "isNew=true" >> $GITHUB_OUTPUT
          fi
  create_pr:
    runs-on: ubuntu-latest
    needs: query_store
    steps:
      - name: Create or Update Pull Request
        if: ${{ steps.compare.output.isNew == true }}
        uses: gr2m/create-or-update-pull-request-action@v1.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          branch: "workflows-update-store"
          commit-message: "chore: update store.json"
          auto-merge: merge
          update-pull-request-title-and-body: true
      
