name: Check Plugin Watchlist
on:
  schedule:
  - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  query_store:
    runs-on: ubuntu-latest
    steps:
      - name: Poll store for fresh data
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            const plugins = await octokit.request(${{ https://plugins.deckbrew.xyz/plugins }});
            console.log(plugins);
